name: urban_tree
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  csv: ^6.0.0
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  sensors_plus: ^6.1.1
  image: ^4.5.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.png
    - assets/data/species_phenology.json
